spring.application.name=BiltUthyrning
spring.datasource.url=jdbc:sqlite:biltuthyrning.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=false
spring.jpa.properties.hibernate.order_inserts=false
spring.jpa.properties.hibernate.order_updates=false
spring.jpa.properties.hibernate.jdbc.fetch_size=0
spring.jpa.properties.hibernate.default_batch_fetch_size=0
spring.jpa.properties.hibernate.id.optimizer.pooled.enabled=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false
spring.jpa.properties.hibernate.jdbc.allow_result_on_close=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:schema.sql

server.port=8080

